name: fastp ci
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-static:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: install build dependencies (Ubuntu)
        run: sudo apt update && sudo apt install -y build-essential nasm cmake
        if: runner.os == 'Linux'

      - name: install build dependencies (macOS)
        run: brew install cmake nasm
        if: runner.os == 'macOS'

      - name: make fastp static
        run: make static -j ${{ steps.cpu-cores.outputs.count }}

      - name: test
        run: ./fastp --version

      - name: test run
        run: ./fastp -i testdata/R1.fq -o /dev/null

  build-link:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: install system libraries
        run: sudo apt update && sudo apt install -y build-essential libisal-dev libdeflate-dev

      - name: make fastp
        run: make -j ${{ steps.cpu-cores.outputs.count }}

      - name: test
        run: ./fastp --version

      - name: test run
        run: ./fastp -i testdata/R1.fq -o /dev/null
